### ISSUE TITLE
Feedback concept

### ISSUE THREAD

**Issue by veerleprins** [lars-ruijs/functional-programming#3]
What strikes me when I look at your "readme" / concept:

- Very clear how you arrived at this research question by means of the news article. 
- Certainly a topical subject, but I do not fully understand the main question. How do you want to determine whether one garage is more at risk of a potential fire than another? As far as I'm looking for this topic online, there are many different factors that influence the burning of electric cars.
- I see you don't have any sub-questions yourself yet. The sub-questions that come to my mind are: 
1. How many parking garages have a charging point?
2. How long, on average, are electric cars at a charging point in a parking garage?
3. How many times a day are the charging stations occupied per parking garage?

- You say well which datasets you want to use! It would certainly strengthen / answer your concept / research question if you could start using that dynamic dataset :)!

**Comment by lars-ruijs** [comment]
Thanks for your feedback Veerle! It is indeed a tricky main question because many other factors influence fire safety. I've also had feedback from others to adjust my research question, so that's what I did. I now have a whole new topic as a concept (we discussed it briefly in the support group). I also added sub-questions and a sketch.
